### ISSUE TITLE
No FST values

### ISSUE THREAD

**Issue by Enso98** [spflanagan/fsthet_analysis#3]
Hi i've started to work with FSThet

I change my vcf file to a genepop file using PGD spider. I compare my genepop with yours and both are similars. 
The file is normally readed with the function my.read.genepop but, when I try to do some FSt test using both funcions fsthet or calc.actual.fst, appears this comment: 
"Error in if (nchar(names(obs.gen[1]))%%2 == 0) { : 
  missing value where TRUE/FALSE needed

I don't know what it means or if my genepop file has missing values. Could you help me to solve it? Thanks in advance.
(i leave an screenshot of my data in R)

![Captura](https://github.com/spflanagan/fsthet_analysis/assets/163324939/fb853ee3-6e19-4c62-89e8-610d672c05b9)

**Comment by spflanagan** [comment]
I've seen this issue before if the populations have not been named properly, and older versions of the program were especially sensitive to small formatting changes. Each population should be specified by "POP" on its own line, before listing the individuals. You can look at the example dataset distributed with the package for guidance. 

Try re-installing the package using `devtools::install_github("spflanagan/fsthet_analysis/fsthet")`, instead of through CRAN. If the problem persists, please provide a reproducible example.

**Comment by Enso98** [comment]
Hi, I've already re-installed the program as you suggested and checked if my data had issues in the POP line but it's ok (even when I read the file in R I can notice that each individual belongs to one of the three populations of my data). However, I'm still having the same response from the console.
I ran your example.genepop.txt data in R too but I did not find differences between my data and yours. What I saw was that my data has 6 digits (for example 120120, where each allele is coded by three digits) and yours has 4 digits. Do you think that the differences between the genepop formats is the reason?. I converted my VCF using PGD SPider. I'm sending my genepop.txt file , which is read by the function my.read.genpop normally.

[dorado_genpop.txt](https://github.com/spflanagan/fsthet_analysis/files/14726850/dorado_genpop.txt)

**Comment by spflanagan** [comment]
It looks like this issue is arising due to one locus having only missing data in one of the populations. I've changed the code so that it won't produce an error message in this case. If you re-install using `devtools::install_github("spflanagan/fsthet_analysis/fsthet")`, this should resolve your problem. 

That being said, I highly recommend filtering your data before using the program so that you are only using loci that have been genotyped in all of your populations, and ideally in most of your individuals. Otherwise your estimates of heterozygosity, and therefore Fst, will not be meaningful. Also note that the Fst-heterozygosity comparison is likely to identify many false positives when only a small number of populations are being compared -- please read the paper that is associated with this package: https://academic.oup.com/jhered/article/108/5/561/3806805

**Comment by Enso98** [comment]
Thanks a lot for your help. I
